### ISSUE TITLE
http://www.turtletest.com/ does not seem to be available anymore

### ISSUE THREAD

**Issue by OlegZee** [lefthandedgoat/turtletestAutomation#2]
Are there sources for the site or alternative domain?

**Comment by lefthandedgoat** [comment]
No I took it down years ago.  I can email you the source if you want, send me an email, my username @ gmail

**Comment by OlegZee** [comment]
Is it an F# project? Can we make it part of this project? I'm thinking how could it be seamlessly integrated, without much of additional instructions in readme file.

**Comment by lefthandedgoat** [comment]
I invited you as a collaborator and I made it public https://github.com/lefthandedgoat/turtletest

I made the site 9 years ago and I dont think I have the shell script I used to install all of the dependencies on Debian.

I just remember that I used debian + mono + postgres

**Comment by OlegZee** [comment]
Thank you for sharing the project, it might take a little more time to have 9 year old stuff up and running. I will get back when I have any progress with this code.

**Comment by OlegZee** [comment]
Closing as I have got access to project
